MONGODB_CONNECTION_STRING: "mongodb+srv://<username>:<password>@<cluster>/<database>?retryWrites=true&w=majority"
MONGODB_DATABASE: "test"
MONGODB_COLLECTION: "test"
SAVE_INTERVAL: 1440 # in minutes (1440 = 24 hours)
