main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Jerzy Szyjut
description: A simple plugin that logs the playtime of players and saves it to the MongoDB database
commands:
  save-playtime:
    description: Saves the playtime data
    permission: playtimelogger.save
  reload-playtime:
    description: Reloads the config
    permission: playtimelogger.reload
permissions:
  playtimelogger.save:
    description: Saves the playtime data
    default: op
  playtimelogger.reload:
    description: Reloads the config
    default: op
  playtimelogger.*:
    description: Grants all other permissions
    default: false
    children:
      playtimelogger.save: true
      playtimelogger.reload: true
